[package]
name = "rusty_gauntlet"
version = "0.0.1"
authors = [ "Thomas Eppers eppi15@yahoo.de", "Florian Oetke mephistopheles@onlinehome.de", "Georg Schäfer georg.peter.schaefer@gmail.com" ]

[dependencies]
glium = "0.14.0"
cgmath = "0.9.1"
image = "0.10.4"
glium_text = "0.9.0"
